#!/bin/bash

# The Feliz2 installation scripts for Arch Linux
# Developed by Elizabeth Mills
# Revision date: 4th December 2016

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.

# This program is distributed in the hope that it will be useful, but
#      WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#            General Public License for more details.

# A copy of the GNU General Public License is available from the Feliz2
#        page at http://sourceforge.net/projects/feliz2/files
#        or https://github.com/angeltoast/feliz2, or write to:
#                 The Free Software Foundation, Inc.
#                  51 Franklin Street, Fifth Floor
#                    Boston, MA 02110-1301 USA

# In this module:

# 1) Declaration of variables and arrays

# Partition variables and arrays
declare -a AddPartList    # Array of additional partitions eg: /dev/sda5
declare -a AddPartMount   # Array of mountpoints for the same partitions eg: /home
declare -a AddPartType    # Array of format type for the same partitions eg: ext4
declare -a PartitionArray # Array of long identifiers
declare -a NewArray       # For copying any array
declare -a NewArray       # For copying any array

declare -a button_start   # Used in listgen
declare -a button_text    # Used in listgen
declare -a button_len     # Used in listgen

declare -A LabellingArray # Associative array of user labels for partitions
declare -A Labelled       # Associative array of labelled partitions
declare -A FileSystem     # Associative array of filesystem types (ext* swap)
BootSize=""               # Boot variable for EasyEFI
RootSize=""               # Root variable for EasyEFI
SwapSize=""               # Swap variable for EasyEFI
HomeSize=""               # Home variable for EasyEFI
HomeType=""               # Home variable for EasyEFI
SwapPartition=""          # eg: /dev/sda3
FormatSwap="N"            # User selects whether to reuse swap
MakeSwap="Y"
SwapFile=""               # eg: 2G
IsSwap=""                 # Result of lsblk test
RootPartition=""          # eg: /dev/sda2
RootType=""               # eg: ext4
Partition=""              # eg: sda1
AutoPart=0                # Flag - changes to 1 if auto-partition is chosen
UseDisk="sda"             # Used if more than one disk
DiskDetails=0             # Size of selected disk
TypeList="ext3 ext4 btrfs xfs" # Partition format types

# Grub & kernel variables
GrubDevice=""             # eg: /dev/sda
Kernel="1"                # Default 1 = LTS
IsInVbox="N"              # Result of test to see if installation is in Virtualbox
OSprober="Y"

# Location variables
CountryCode=""            # eg: GB ... for mirrorlist
CountryLocale=""          # eg: en_GB.UTF-8
Countrykbd=""             # eg: uk
ZONE=""                   # eg: Europe For time
SUBZONE=""                # eg: London

# Desktop environment, display manager and greeter variables
DesktopEnvironment=""     # eg: xfce
DisplayManager=""         # eg: lightdm
Greeter=""                # eg: lightdm-gtk-greeter (Not required for some DMs)

# Root and user variables
HostName=""               # eg: arch-linux
UserName=""               # eg: archie
Scope=""                  # Installation scope ... 'Full' or 'Basic'

# Global user input variables
Response=""
Result=""

# Miscellaneous
Backtitle="~ The Feliz install scripts for Arch Linux ~"
helpMESSAGE=""            # Used by help system
declare -a Options        # For listgen functions

# ---- Partitioning ----
PartitioningOptions="cfdisk guided auto leave"
LongPart[1]="Open cfdisk so I can partition manually"
LongPart[2]="Guided manual partitioning tool"
LongPart[3]="Allow feliz to partition the whole device"
LongPart[4]="Leave it as it is"
# EFI
EFIPartitioningOptions="guided auto leave"
LongPartE[1]="Guided manual partitioning tool"
LongPartE[2]="Allow feliz to partition the whole device"
LongPartE[3]="Leave it as it is"

# ---- Arrays for extra Applications ----
CategoriesList="Accessories Desktop_Environments Graphical Internet Multimedia Office Programming Window_Managers"
Categories[1]="Accessories"
Categories[2]="Desktop_Environments"
Categories[3]="Graphical"
Categories[4]="Internet"
Categories[5]="Multimedia"
Categories[6]="Office"
Categories[7]="Programming"
Categories[8]="Window_Managers"
# Accessories
Accessories="brasero conky gedit gparted"
LongAccs[1]="Brasero - Disc burning application from Gnome"
LongAccs[2]="Conky   - Desktop time and system information"
LongAccs[3]="Gedit   - The text editor from Gnome"
LongAccs[4]="Gparted - Tool to make/delete/resize partitions"
# Desktops
Desktops="Budgie Cinnamon Deepin Gnome KDE LXDE LXQt Mate Xfce"
LongDesk[1]="Budgie   - Modern desktop focusing on simplicity & elegance"
LongDesk[2]="Cinnamon - Slick DE from the Mint team      "
LongDesk[3]="Deepin   - The Deepin Desktop Environment"
LongDesk[4]="Gnome    - Full-featured, modern DE"
LongDesk[5]="KDE      - Plasma 5 and accessories pack"
LongDesk[6]="LXDE     - Traditional, lightweight DE"
LongDesk[7]="LXQt     - Lightweight and modern Qt DE"
LongDesk[8]="Mate     - Traditional DE from the Mint team"
LongDesk[9]="Xfce     - Lightweight, highly configurable DE"
# Graphical
Graphical="evince gimp imagemagick gthumb simple-scan xsane"
LongGraph[1]="Evince      - Reader for PDF & other document formats"
LongGraph[2]="GIMP        - Advanced image editing suite"
LongGraph[3]="Imagemagick - Command-line image manipulation"
LongGraph[4]="Gthumb      - Image viewer & basic editor"
LongGraph[5]="Simple-scan - A simple scanner GUI"
LongGraph[6]="Xsane       - Full-featured GTK-based sane frontend"
# Internet
Internet="chromium epiphany filezilla firefox qbittorrent thunderbird transmission-gtk"
LongNet[1]="Chromium     - Open source web browser from Google     "
LongNet[2]="Epiphany     - Gnome WebKitGTK+ browser (aka Web)"
LongNet[3]="Filezilla    - Fast & reliable FTP, FTPS & SFTP client"
LongNet[4]="Firefox      - Extensible browser from Mozilla"
LongNet[5]="Qbittorrent  - Open source BitTorrent client"
LongNet[6]="Thunderbird  - Feature-rich email client from Mozilla"
LongNet[7]="Transmission - Easy-to-use BitTorrent client"
# Multimedia
Multimedia="avidemux-gtk banshee handbrake openshot vlc xfburn"
LongMulti[1]="Avidemix  - Easy-to-use video editor               "
LongMulti[2]="Banshee   - Feature-rich audio player"
LongMulti[3]="Handbrake - Simple yet powerful video transcoder"
LongMulti[4]="Openshot  - Easy-to-use non-linear video editor"
LongMulti[5]="VLC       - Middleweight video player"
LongMulti[6]="Xfburn    - GUI CD burner"
# Office
Office="abiword gnumeric libreoffice orage scribus"
LongOffice[1]="Abiword     - Full-featured word processor        "
LongOffice[2]="Gnumeric    - Spreadsheet program from GNOME"
LongOffice[3]="LibreOffice - Open-source office software suite"
LongOffice[4]="Orage       - Calendar & task manager (incl with Xfce)"
LongOffice[5]="Cribus      - Desktop publishing program"
# Programming
Programming="bluefish codeblocks emacs geany git netbeans"
LongProg[1]="Bluefish   - GTK+ IDE with support for Python plugins  "
LongProg[2]="CodeBlocks - Open source & cross-platform C/C++ IDE"
LongProg[3]="Emacs      - Extensible, customizable text editor"
LongProg[4]="Geany      - Advanced text editor & IDE"
LongProg[5]="Git        - Open source distributed version control system"
LongProg[6]="Netbeans   - Integrated development environment (IDE)"
# WindowManagers
WindowManagers="Enlightenment Fluxbox Openbox cairo-dock docky fbpanel tint2"
LongWMs[1]="Enlightenment - Window manager and toolkit"
LongWMs[2]="Fluxbox       - Light, fast and versatile WM"
LongWMs[3]="Openbox       - Lightweight, powerful & configurable stacking WM"
LongWMs[4]="Cairo         - Customizable dock & launcher application"
LongWMs[5]="Docky         - For opening applications & managing windows"
LongWMs[6]="Fbpanel       - Desktop panel"
LongWMs[7]="Tint2         - Desktop panel"
