#!/bin/bash
  
testbed() {
  
# 
getkeymap
setlocale
SetTimeZone

}

# ~~~~~~~
# Execute
# ~~~~~~~
  
# First check for external functions and variables files
  if [[ -f `pwd`/squifffuncs ]]; then
    source squifffuncs
  else
    echo "missing file: squifffuncs"
    exit 1
  fi
  
  if [[ -f `pwd`/squiffparts ]]; then
    source squiffparts
  else
    echo "missing file: squiffparts"
    exit 1
  fi
  
  if [[ -f `pwd`/squiffdesktop ]]; then
    source squiffdesktop
  else
    echo "missing file: squiffdesktop"
    exit 1
  fi
 
  if [[ -f `pwd`/squifflistgen ]]; then
    source squifflistgen
  else
    echo "missing file: squifflistgen"
    exit 1
  fi
  
  # Various variables
  UEFI=0
#  RootPartition="sda10"
#  RootType="ext4"
#  SwapPartition="sda7"
#  PartitionList="sda2 sda3"
#  AddPartList[0]="sda9"
#  AddPartLabel[0]="/home"
#  AddPartType[0]="ext4"
#  AddPartList[1]="sda5"
#  AddPartLabel[1]="/spare"
#  AddPartType[1]="ext4"
#  GrubDevice="/dev/sda"
#  CountryCode="GB"
#  CountryLocale="en_GB.UTF-8"
#  Countrykbd="uk"
#  ZONE="Europe"
#  SUBZONE="London"
#  DesktopEnvironment="xfce4"
#  DisplayManager="lightdm"
#  Greeter="lightdm-gtk-greeter"
#  LuxuriesList="firefox libreoffice-still geany pamac-aur"
#  HostName="ArchLinux"
#  RootPassword="Root"
#  UserName="archie"
#  UserPassword="Linux"
#  DesktopEnvironment="Gnome"
# Colours
Red='\e[0;31m';
Gre='\e[0;32m';
Yel='\e[0;33m';
Blu='\e[0;34m';
Pur='\e[0;35m';
Cya='\e[0;36m';
BRed='\e[1;31m';
BGre='\e[1;32m';
BYel='\e[1;33m';
BBlu='\e[1;34m';
BPur='\e[1;35m';
BCya='\e[1;36m';
UYel='\e[4;33m';
NoCol='\e[0;00m';  

# Call the function 'testbed' holding code to be tested
testbed
echo $* # Add any variables needed for viewing before exit
echo "End of test"
  
exit
  
  # Code for checking arrays
  Counter=0
  for i in ${AddPartList[@]}	
  do
    echo ${AddPartList[$Counter]}
    echo ${AddPartLabel[$Counter]} 
    echo ${AddPartType[$Counter]}
    Counter=$((Counter+1))
  done
  
