#!/bin/bash

# Part of the Feliz Arch Linux Installation Scripts
# This script is to be run after Xfce is first started
# Developed by Elizabeth Mills

# Thunar actions
echo "Copying Thunar actions" > feliz-setup.log
cp -f uca.xml ~/.config/Thunar/ &>> feliz-setup.log # This is a copy of my xfce actions
cp -f uca.xml ~/.config/Thunar/ # It is necessary to repeat it as Xfce overwrites it the first time

# Conky autostart
echo "Testing for Conky" >> feliz-setup.log
case `whereis conky` in
  "conky:") echo "Conky not installed" >> feliz-setup.log
  ;;
  *) echo "Conky installed" >> feliz-setup.log
  #  cp conky.desktop ~/.config/autostart/ &>> feliz-setup.log
esac

# Delete this script after first use ...
mv feliz-xfce feliz-setup &>> feliz-setup.log

