#!/bin/bash

# Part of the Feliz Arch Linux Installation Scripts
# This script is to be run after Xfce is first started
# Developed by Elizabeth Mills

FelizActions() {
# Thunar actions
echo "Copying Thunar actions" > /etc/feliz-setup.log
cp -f /etc/xdg/xfce4/uca.xml /home/UserName/.config/Thunar/ &>> /etc/feliz-setup.log
cp -f /etc/xdg/xfce4/uca.xml /home/UserName/.config/Thunar/ # It is necessary to repeat it as Xfce overwrites it the first time

# Conky autostart
echo "Testing for Conky" >> /etc/feliz-setup.log
case `whereis conky` in
  "conky:") echo "Conky not installed" >> /etc/feliz-setup.log
  ;;
  *) echo "Conky installed" >> /etc/feliz-setup.log
  if [ ! -d /home/UserName/.config/autostart ]; then
      echo "No autostart directory found" >> /etc/feliz-setup.log
    #  mkdir /home/UserName/.config/autostart/
    else 
      echo "Autostart directory found" >> /etc/feliz-setup.log
    fi
    cp /etc/xdg/xfce4/conky.desktop /home/UserName/.config/autostart/ &>> /etc/feliz-setup.log
esac

# Delete this script after first use ...
mv /etc/xdg/xfce4/feliz-xfce feliz-setup &>> /etc/feliz-setup.log
}
