#!/bin/bash

# Part of the Feliz Arch Linux Installation Scripts
# This script is to be run after Xfce is first started
# Developed by Elizabeth Mills

UserName=`whoami`

# Thunar actions
if [ ! -d ~/.config/Thunar ]; then
  mkdir ~/.config/Thunar
fi
cp -f /etc/uca.xml ~/.config/Thunar/
cp -f /etc/uca.xml ~/.config/Thunar/ # It is necessary to repeat it as Xfce overwrites it the first time

# Conky autostart
case `whereis conky` in
  "conky:") echo "conky not installed" > /etc/feliz-setup.log
  ;;
  *) if [ ! -d ~/.config/autostart ]; then
      mkdir ~/.config/autostart/
    fi
    cp /etc/conky.desktop ~/.config/autostart/
    conky
esac

# After first use ...
sed -i '/feliz-setup/ d' /home/${UserName}/xinitrc # Remove line from xinitrc
rm -f /home/${UserName}/feliz-setup                # Then delete this script
