#!/bin/bash

# Part of the Feliz Arch Linux Installation Scripts
# This script changes various settings after installation of Xfce
# Developed by Elizabeth Mills

UserName=`whoami`

# Conky autostart
case `whereis conky` in
  "conky:") echo "conky not installed" > /etc/feliz-setup.log
  ;;
  *) mkdir /home/$UserName/.config/autostart/
    cp /etc/conky.desktop /home/$UserName/.config/autostart/
    conky
esac

# Thunar actions
mkdir /home/${UserName}/.config/Thunar
cp /etc/uca.xml /home/${UserName}/.config/Thunar/
