#!/bin/bash

# shared - Part of the Feliz Arch Linux Installation Script

# Developed by Elizabeth Mills, incorporating some code adapted from the
# excellent Evo/Lution script by Carl Duff and AUI scripts by HelmuthDU.

#
# Partition variables and arrays
#
declare -a AddPartList	  # Array of additional partitions eg: /dev/sda5
declare -a AddPartMount   # Array of mountpoints for the same partitions eg: /home
declare -a AddPartType  	# Array of format type for the same partitions eg: ext4
declare -a PartitionArray # List of long identifiers
declare -a NewArray       # For copying any array
declare -A LabellingArray # To hold full details of user labels for partitions
declare -A Labelled       # Store labels
declare -A FileSystem     # Store filesystem types (ext* swap)
SwapPartition=""  # eg: /dev/sda3
FormatSwap="N"    # User selects whether to reuse swap
MakeSwap="Y"
SwapFile=""       # eg: 2G
IsSwap=""         # Result of lsblk test
RootPartition=""  # eg: /dev/sda2
RootType=""       # eg: ext4
Partition=""      # eg: sda1
AutoPart=0        # Flag - changes to 1 if auto-partition is chosen
UseDisk="sda"     # Used if more than one disk
DiskDetails=0     # Size of selected disk
#
# Grub, kernel & EFI variables
#
GrubDevice=""     # eg: /dev/sda
Kernel="1"        # Default 1 = LTS
IsInVbox=""       # Result of test to see if installation is in Virtualbox
DualBoot="N"      # Ready for dual-booting option
EFIPartition=""   # Will hold EFI partition mountpoint in format "/dev/sda1"
OSprober="Y"
#
# Location variables
#
CountryCode=""    # eg: GB ... for mirrorlist
CountryLocale=""  # eg: en_GB.UTF-8
Countrykbd=""     # eg: uk
ZONE=""           # eg: Europe For time
SUBZONE=""        # eg: London
#
# Desktop environment, display manager and greeter variables
#
DesktopEnvironment="None"  # eg: xfce4
GoodiesXfce=""
GoodiesGnome=""
GoodiesOpenbox=""
DisplayManager=""      # eg: lightdm
Greeter=""             # eg: lightdm-gtk-greeter (Not required for some DMs)
#
# Root and user variables
#
HostName=""  # eg: arch-linux
UserName=""  # eg: archie
Scope=""     # Installation scope ... 'Full' or 'Basic'
#
# Global user input variables
#
Response="" 
Result=""
#
# ---- Extras ----
#
Categories="Accessories Desktop_Environments Graphical Internet Multimedia Office Programming Window_Managers"
Accessories="brasero cairo-dock conky docky gnome-calculator gedit gparted nautilus xfce4-terminal yaourt"
LongAccs[1]="Brasero - Disc burning application from Gnome          "
LongAccs[2]="Cairo Dock - Customizable dock and launcher application"
LongAccs[3]="Conky - Desktop time and system information"
LongAccs[4]="Docky - For opening applications and managing windows"
LongAccs[5]="gCalculator - Calculator for your taskbar"
LongAccs[6]="gEdit - The text editor from Gnome"
LongAccs[7]="GParted - make/delete/resize partitions"
LongAccs[8]="Nautilus - The file-manager from Gnome"
LongAccs[9]="Terminal - The Xfce terminal emulator"
LongAccs[10]="Yaourt - Easy to use AUR package installer"
Desktops="Cinnamon Gnome KDE LXDE LXQt Mate Xfce"
LongDesk[1]="Cinnamon - Slick DE from the Mint team"
LongDesk[2]="Gnome - Full-featured, modern DE"
LongDesk[3]="KDE - Plasma 5 and accessories pack"
LongDesk[4]="LXDE - Traditional, lightweight DE"
LongDesk[5]="LXQt - Lightweight and modern Qt DE"
LongDesk[6]="Mate - Traditional DE from the Mint team"
LongDesk[7]="Xfce - Lightweight, highly configurable DE"
Graphical="evince gimp imagemagick gthumb simple-scan xsane"
LongGraph[1]="Evince - Reader for PDF and other document formats"
LongGraph[2]="GIMP - Advanced image editing suite"
LongGraph[3]="Imagemagick - Command-line image manipulation"
LongGraph[4]="gThumb - Image viewer & basic editor"
LongGraph[5]="Simple-Scan - A simple scanner GUI"
LongGraph[6]="Xsane - A full-featured GTK-based sane frontend"
Internet="chromium epiphany filezilla firefox qbittorrent thunderbird transmission-gtk"
LongNet[1]="Chromium - Open source web browser from Google     "
LongNet[2]="Epiphany - Gnome WebKitGTK+ browser (aka Web)"
LongNet[3]="Filezilla - Fast and reliable FTP, FTPS & SFTP client"
LongNet[4]="Firefox - Extensible browser from Mozilla"
LongNet[5]="qBittorent - Open source BitTorrent client"
LongNet[6]="Thunderbird - Feature-rich email client from Mozilla"
LongNet[7]="Transmission - Easy-to-use BitTorrent client"
Multimedia="avidemux-gtk banshee handbrake openshot vlc xfburn"
LongMulti[1]="Avidemux - Simple video editor               "
LongMulti[2]="Banshee - Feature-rich audio player"
LongMulti[3]="Handbrake - Simple yet powerful video transcoder"
LongMulti[4]="Openshot - Easy-to-use non-linear video editor"
LongMulti[5]="VLC - Middleweight video player"
LongMulti[6]="Xfburn"
Office="abiword gnumeric libreoffice orage scribus"
LongOffice[1]="Abiword - Full-featured word processor        "
LongOffice[2]="Gnumeric - Spreadsheet program from GNOME"
LongOffice[3]="LibreOffice - Open-source office software suite"
LongOffice[4]="Orage - Calendar and task manager (incl with Xfce)"
LongOffice[5]="Scribus - Desktop publishing program"
Programming="bluefish codeblocks emacs geany git netbeans"
LongProg[1]="Bluefish - GTK+ IDE with support for Python plugins  "
LongProg[2]="Code::Blocks - Open source & cross-platform C/C++ IDE"
LongProg[3]="Emacs - extensible, customizable text editor"
LongProg[4]="Geany - Advanced text editor & IDE"
LongProg[5]="Git - open source distributed version control system"
LongProg[6]="Netbeans - Integrated development environment (IDE)"
WindowManagers="Enlightenment Fluxbox JWM Openbox"
LongWMs[1]="Enlightenment"
LongWMs[2]="Fluxbox"
LongWMs[3]="JWM"
LongWMs[4]="Openbox"
#
# Include files
#
if [[ -f `pwd`/various ]]; then
  source various
else
  echo "missing file: various"
  exit 1
fi
if [[ -f `pwd`/partitioning ]]; then
  source partitioning
else
  echo "missing file: partitioning"
  exit 1
fi
if [[ -f `pwd`/desktop ]]; then
  source desktop
else
  echo "missing file: desktop"
  exit 1
fi
if [[ -f `pwd`/listgen ]]; then
  source listgen
else
  echo "missing file: listgen"
  exit 1
fi

#
# Common cli functions
#
read_timed() { # $1 = text to display; $2 = duration
  T_COLS=`tput cols`
  lov=${#1}
  if [ $2 ]; then
    tim=$2
  else
    tim=2
  fi
  if [ ${lov} -lt ${T_COLS} ]; then
    stpt=$(( ($T_COLS - $lov) / 2 ))
    EMPTY="$(printf '%*s' $stpt)"
  else
    EMPTY=""
  fi
  read -t ${tim} -p "$EMPTY $1"
  echo
}


print_heading() {
  clear
  T_COLS=`tput cols`
  tput cup 1 $((($T_COLS/2)-20))
  printf "~ feliz! The Arch Linux Installation Script ~\n"
  printf "%$(tput cols)s\n"|tr ' ' '-'
}

TPecho() { # For displaying status while running on auto
  echo
  CurrentTime=$(date +%s)
  Difference=$(( $CurrentTime-$StartTime ))
  DIFFMIN=$(( $Difference/60 ))
  DIFFSEC=$(( $Difference % 60 ))
  T_COLS=`tput cols`
  tput bold
  lov=${#1}
  if [ ${lov} -lt ${T_COLS} ]; then
    stpt=$(( ($T_COLS - $lov) / 3 ))
    EMPTY="$(printf '%*s' $stpt)"
    echo -e "$EMPTY ${DIFFMIN}m ${DIFFSEC}s - $1 \n"
  else
    echo -e "${DIFFMIN}m ${DIFFSEC}s - $1 \n"
  fi
  tput sgr0
  echo
}

ReflectorMirrorList() { # Use reflector (added to archiso) to generate fast mirror list
  TPecho "Using Reflector to generate mirrorlist"
  reflector --verbose -l 5 --sort rate --save /etc/pacman.d/mirrorlist 2>> feliz.log
  if [ $? -gt 0 ]; then
    LocalMirrorList
  else
    chmod +r /etc/pacman.d/mirrorlist 2>> feliz.log
  fi
}

LocalMirrorList() { # In case Reflector fails, generate and save a shortened 
  # mirrorlist of only the mirrors defined in the CountryCode variable.
	TPecho "Reflector not available - generating local mirrorlist instead"
	URL="https://www.archlinux.org/mirrorlist/?country=${CountryCode}&use_mirror_status=on"
	MirrorTemp=$(mktemp --suffix=-mirrorlist) 2>> feliz.log
	# Use curl to get list of mirrors from the Arch mirrorlist ${URL} to ${MirrorTemp}
	curl -so ${MirrorTemp} ${URL} 2>> feliz.log
	# Use sed to filter entries
	sed -i 's/^#Server/Server/g' ${MirrorTemp} 2>> feliz.log
	# Make a safe copy of existing mirrorlist
	mv -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig 2>> feliz.log
	# Replace existing mirrorlist with new local mirrorlist
	mv -f ${MirrorTemp} /etc/pacman.d/mirrorlist 2>> feliz.log
	chmod +r /etc/pacman.d/mirrorlist 2>> feliz.log
}
